### ISSUE TITLE
Novo tile de calendário para Eventos

### ISSUE THREAD

**Issue by taniaa** [plonegovbr/brasil.gov.tiles#111]
No último sprint em que a comunidade PloneGov-BR participou para colocar o site softwarelivre.gov.br em Plone 4 de Portal Padrão, identificamos a necessidade de criar um tile de calendário para Eventos (tipo de conteúdo padrão do Plone). Este seria um dos destaques mais importantes para este site e também já foi apontado como necessidade pela SAC (identificado em treinamento fornecido pela Secom). O tile Agenda de Autoridades atende a LAI, mas não possibilita agendar e destacar eventos diversos.

**Comment by hvelarde** [comment]
o collective.cover inclui um tile de calendário baseado no código do portlet padrão do Plone (refs. https://github.com/collective/collective.cover/pull/632).
