### ISSUE TITLE
Novo tile para a rede social livre Diáspora

### ISSUE THREAD

**Issue by taniaa** [plonegovbr/brasil.gov.tiles#112]
No último sprint em que a comunidade PloneGov-BR participou para colocar o site softwarelivre.gov.br em Plone 4 de Portal Padrão, identificamos a necessidade de criar o tile do Diáspora. Este novo tile precisará ter comportamento semelhante ao tile Social atual que permite trazer curtidas do Facebook e lista de últimos posts do Twitter. Antes é preciso avaliar o que o Diáspora dispõe de dado para utilizarmos no novo tile.

**Comment by hvelarde** [comment]
Têm informação de como implementar isso?

**Comment by taniaa** [comment]
Oi, Hector.

Sondei num grupo SL do Telegram e me disseram que o Diaspora "não possui nada como uma API bonitinha" ainda e mal tem documentação. Foi feito em PHP e pra isso tem o source do paperbod (https://github.com/dkodnik/paperbod).

Sendo assim, melhor fechar a issue, né?
