### ISSUE TITLE
Corrigir teste para funcionar com collective.cover > 1.0a6

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#125]
Utilizando o collective.cover > 1.0a6, os testes falham dando o erro:

	Error in test test_tile_is_empty (brasil.gov.tiles.tests.test_mediacarousel_tile.MediaCarouselTileTestCase)
	Traceback (most recent call last):
	  File "/home/xxx/pythons/python273/lib/python2.7/unittest/case.py", line 318, in run
	    self.setUp()
	  File "/home/xxx/brasil.gov.tiles/src/brasil/gov/tiles/tests/test_mediacarousel_tile.py", line 27, in setUp
	    self.cover = self.portal['frontpage']
	  File "/home/xxx/brasil.gov.tiles/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 784, in __getitem__
	    raise KeyError, key
	KeyError: 'frontpage'

Isso ocorre porque depois do commit https://github.com/collective/collective.cover/commit/61441e3742be5611c51dc8edab0dddeec4babf3f do @hvelarde, o objeto 'frontpage' deixou de ser criado. Ver discussão em: https://github.com/plonegovbr/brasil.gov.portal/issues/170

**Comment by hvelarde** [comment]
confirmed in: https://travis-ci.org/plonegovbr/brasil.gov.tiles/builds/59301677

**Comment by idgserpro** [comment]
Não esquecer de, após mudar a versão do collective.cover, consertar o fix presente no commit https://github.com/plonegovbr/brasil.gov.portal/commit/6644b6e05540ec90a080dbd69f4ac859ec88b2d7 em brasil.gov.portal.

Isso é necessário uma vez que o fix https://github.com/collective/collective.cover/issues/450 foi corrigido e serão necessárias adaptações.
