### ISSUE TITLE
Error: Bad constraint 1.2.3 plone.app.querystring>=1.2.5

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#126]
O brasil.gov.tiles tem como dependência o collective.nitf. A nova versão do collective.nitf 1.0b5 pede o [plone.app.querystring>=1.2.5](https://github.com/collective/collective.nitf/blob/master/setup.py#L56). Mas plone.app.querystring>=1.2.5 entra em conflito com o plone.app.querystring 1.2.3, que é a [versão recomendada pelo plone 4.3.x](http://dist.plone.org/release/4.3-latest/versions.cfg).

**Comment by hvelarde** [comment]
acho que só precisa colocar ``plone.app.querystring = 1.2.5`` no:

https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg

**Comment by idgserpro** [comment]
O brasil.gov.tiles no utiliza o https://github.com/plonegovbr/portal.buildout/blob/master/buildout.d/versions.cfg. Acho que tem que ser alterado no [buildout.cfg](https://github.com/plonegovbr/brasil.gov.tiles/blob/master/buildout.cfg#L41)

**Comment by idgserpro** [comment]
Feito no #26.

**Comment by idgserpro** [comment]
Esse relato deixou de ser válido, uma vez que a nova versão do Plone (4.3.6), atualizou o plone.app.querystring para [1.2.5](https://github.com/plone/Installers-UnifiedInstaller/blob/4.3.6/base_skeleton/versions.cfg#L160).

A pinagem do  plone.app.querystring feita no https://github.com/plonegovbr/brasil.gov.tiles/pull/128, deve se removida.

**Comment by hvelarde** [comment]
@idgserpro por favor atualize o PR; de qualquer jeito olhe que a gente ainda não pode atualizar para Plone 4.3.6 até fechar https://github.com/plonegovbr/brasil.gov.agenda/issues/32
