### ISSUE TITLE
Implementar a lógica de vocabulários internacionalizados no campo "choices" dos tiles.

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#127]
Como relatado no #123, não basta simplesmente alterar as strings em português dos `choices` de um tile. É necessário, como ação futura de melhoria:
- Criar uma constante internacionalizada dos termos que popularão as opções;
- Criar um vocabulário com um token baseado nessa constante de forma normalizada, mas com o título internacionalizado, e, na definição do tile, ao invés de `values` usar esse vocabulário;

```
    form.no_omit('variacao_titulo')
    form.omitted(IDefaultConfigureForm, 'variacao_titulo')
    variacao_titulo = schema.Choice(
        title=u'Variação de Título',
        # values=(u'Normal',
        #         u'Grande',
        #         u'Gigante'),
        vocabulary = "brasil.gov.tiles.vocabularies.title_change",
        default=u'Normal',
        required=True,
    )

```
- Dotado do token e to vocabulário, a variável [tamanhos](https://github.com/plonegovbr/brasil.gov.tiles/pull/124/files) passa a usar como chave os tokens persistidos;
- Criação de upgradeSteps percorrendo **todo o portal** alterando o valor persistido antigo pelo equivalente do token.

Alguns arquivos onde serão necessárias as criações desses vocabulários: tiles/banner_rotativo.py,
tiles/basic.py, tiles/nitf.py.

**Comment by hvelarde** [comment]
:+1:

**Comment by hvelarde** [comment]
essa funcionalidade foi removida do IDG v2 pelo tanto isso aqui não é mais válido.
