### ISSUE TITLE
Porque o collective.cover é pinado?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#130]
Porque o collective.cover é [pinado](https://github.com/plonegovbr/brasil.gov.tiles/blob/master/buildout.cfg#L44)? Pergunto isso porque, pelo menos na teoria, o brasil.gov.tiles é independente do brasil.gov.portal. Se ele não fosse pinado, erros como https://github.com/plonegovbr/brasil.gov.tiles/issues/125, poderiam ser detectados e corrigidos mais cedo.

**Comment by hvelarde** [comment]
o collective.cover está pinado porque a versão 1.0a10 saiu com um [bug grave](https://github.com/collective/collective.cover/issues/466) é prefiro manter a 1.0a9 em produção até liberar a 1.0a11.
