### ISSUE TITLE
Tamanho das imagens no tile banner

### ISSUE THREAD

**Issue by agnogueira** [plonegovbr/brasil.gov.tiles#133]
O tile de banner apresenta um problema com a dimensão das imagens no Firefox e Internet Explorer.
As imagens adicionadas neste tile não obedecem a regra de de tamanho máximo, sendo exibidas cropadas no Firefox e IE como pode ser visto nas imagens a seguir.

Firefox:
![print_firefox](https://cloud.githubusercontent.com/assets/1030139/11211932/feb80498-8d19-11e5-8884-e1ec377046f9.png)

Chrome:
![print_google_chrome](https://cloud.githubusercontent.com/assets/1030139/11211931/feb2e0f8-8d19-11e5-9a5c-ffe05dd5c45c.png)

**Comment by agnogueira** [comment]
Para corrigir me parece que precisamos apenas remover o alinhamento do .tile-banner

**Comment by hvelarde** [comment]
esse problema ainda existe na versão mais recente do branch 1.x ou 2.x?

**Comment by hvelarde** [comment]
a customização do tile de banner foi removida, caso o problema persista terá que ser corrigido upstream no collective.cover (refs. #205)
