### ISSUE TITLE
Tile embed existe no código, mas não está no configure.zcml e sim no overrides.zcml.

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#134]
Temos o [código](https://github.com/plonegovbr/brasil.gov.tiles/blob/1ed35bed63c3c6042d4d9604e1c970a24b273d37/src/brasil/gov/tiles/tiles/embed.py) de [implementação](https://github.com/plonegovbr/brasil.gov.tiles/blob/cf4895153744780f76ca02b3429d32f74cf08067/src/brasil/gov/tiles/tiles/templates/embed.pt) do tile embed, mas ele não está disponível no [configure.zcml](https://github.com/plonegovbr/brasil.gov.tiles/blob/5430d930a3e6ed8fb739eb9562c488d50ea452ca/src/brasil/gov/tiles/tiles/configure.zcml) e sequer no registry.xml. Esse tile é referenciado no [manual de gestão de conteúdo](http://www.secom.gov.br/orientacoes-gerais/comunicacao-digital/gestao-manual-portal-modelo-governo-federal-dez2014.pdf).

No registro de configuração de um novo portal IDG 1.0.5, temos os seguintes tiles registrados (veja que não temos o embed):

``` python
[u'agenda', u'audio', u'audiogallery', u'collective.cover.banner', u'collective.cover.carousel', u'collective.cover.collection', u'collective.cover.list', u'collective.cover.richtext', u'em_destaque', u'mediacarousel', u'nitf', u'social', u'standaloneheader', u'video', u'videogallery', u'banner_rotativo']
```

Qual foi a motivação desse overrides? @rodfersou alguma idéia? Aos demais, alguma idéia do porque ele não aparece registrado?

**Comment by agnogueira** [comment]
Me parece que ele está no [override] (https://github.com/plonegovbr/brasil.gov.tiles/blob/dc516885631d31b4bf0ef998650d54d46ee452ee/src/brasil/gov/tiles/tiles/overrides.zcml)

Esse tile é padrão do cover, interessante descobrir porque é duplicado aqui.

**Comment by idgserpro** [comment]
Deve ter ocorrido algum desenvolvimento "em paralelo" na época, assim como algumas coisas do collective.nitf presentes em brasil.gov.portal. Vou mudar o título da issue e complementar com relação ao registro.

**Comment by idgserpro** [comment]
Por causa desse overrides, a nova versão a13 do collective.cover (que não saiu ainda) quebra os ícones dos que tem overrides, pois agora temos o prefixo `/img` para o ícone dos tiles mas o overrides.zcml não.

Versão atual:

![selecao_130](https://cloud.githubusercontent.com/assets/8203476/13287445/e60b2988-dae5-11e5-8cd3-51981cc68264.png)

Com o pre-release a13:

![selecao_131](https://cloud.githubusercontent.com/assets/8203476/13287453/ef4eaae2-dae5-11e5-867f-e8070f120ffa.png)

Para testar: pegue o [último commit](https://github.com/plonegovbr/brasil.gov.tiles/commit/918d7eae76a585cf7c8fc32a242aae49a680e76c) do brasil.gov.tiles e o último de [collective.cover](https://github.com/collective/collective.cover/commit/33ce290ee70656245f5763c1ab367ad49fd194c2).

Novamente, @rodfersou: lembra da motivação de porque esse overrides.zcml existe? Isso é importante saber para determinarmos o direcionamento da correção. Se o overrides.zcml não é mais necessário, ele pode ser removido junto com as customizações e esse erro do ícone resolve; se ele é necessário, teremos de alterá-lo com essas novas referências quando for atualizar o collective.cover.

**Comment by rodfersou** [comment]
Os overrides existem para customizar tiles do ``collective.cover`` quando necessário.

Não me lembro da motivação para cada override, mas podemos procurar isso no histórico do github.

* https://github.com/plonegovbr/brasil.gov.tiles/commits/master/src/brasil/gov/tiles/tiles/basic.py
* https://github.com/plonegovbr/brasil.gov.tiles/commits/master/src/brasil/gov/tiles/tiles/banner.py
* https://github.com/plonegovbr/brasil.gov.tiles/commits/master/src/brasil/gov/tiles/tiles/collection.py
* https://github.com/plonegovbr/brasil.gov.tiles/commits/master/src/brasil/gov/tiles/tiles/list.py
* https://github.com/plonegovbr/brasil.gov.tiles/commits/master/src/brasil/gov/tiles/tiles/embed.py
* https://github.com/plonegovbr/brasil.gov.tiles/commits/master/src/brasil/gov/tiles/tiles/carousel.py

**Comment by rodfersou** [comment]
Algumas vezes não podiamos esperar por um release do collective.cover, então tivemos que alterar o tile no nosso pacote.

**Comment by rodfersou** [comment]
Sugiro que seja revisado caso a caso o que o collective.cover ja corrige para desfazer aos poucos essas customizações.
Em alguns casos ainda abrir issues no collective.cover para corrigir diretamente la.

**Comment by idgserpro** [comment]
"Contaminamos" demais esse relato, abrimos outro pra resolver essa questão do icon em https://github.com/plonegovbr/brasil.gov.tiles/issues/140

**Comment by hvelarde** [comment]
o overrides do tile de embed foi removido no IDG v2 por tanto isso aqui não é mais válido (refs. #210).
