### ISSUE TITLE
O tile social deveria ter a opção de escolher qual rede social aparece primeiro?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#135]
Hoje, o tile social mostra primeiro o facebook e depois o twitter. Seria o caso de permitir a escolha específica de uma rede social para mostrar?

**Comment by agnogueira** [comment]
Esse tile será descontinuado, pois os códigos utilizados em boa parte não funcionam mais.
Podemos fechar essa @idgserpro ?
