### ISSUE TITLE
collective.cover 1.0a13 quebra os ícones de tiles no overrides.zcml

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#140]
Por causa desse overrides, a nova versão a13 do collective.cover (que não saiu ainda) quebra os ícones dos que tem overrides, pois agora temos o prefixo `/img` para o ícone dos tiles mas o overrides.zcml não.

Versão atual:

![selecao_130](https://cloud.githubusercontent.com/assets/8203476/13287445/e60b2988-dae5-11e5-8cd3-51981cc68264.png)

Com o pre-release a13:

![selecao_131](https://cloud.githubusercontent.com/assets/8203476/13287453/ef4eaae2-dae5-11e5-867f-e8070f120ffa.png)

Para testar: pegue o [último commit](https://github.com/plonegovbr/brasil.gov.tiles/commit/918d7eae76a585cf7c8fc32a242aae49a680e76c) do brasil.gov.tiles e o último de [collective.cover](https://github.com/collective/collective.cover/commit/33ce290ee70656245f5763c1ab367ad49fd194c2).

**Comment by idgserpro** [comment]
Após a correção e apenas após o lançamento do release a13, será necessário pinar no setup.py do pacote para pegar acima ou igual a versão 1.0a13, uma vez que quebrará os ícones dos ambientes que tiverem versões menores.

**Comment by rodfersou** [comment]
Isso acontece por que houve uma reorganização do conteúdo estático do cover (mudança de pastas), e será necessário um upgrade step no brasil.gov.tiles para corrigir os caminhos.

**Comment by idgserpro** [comment]
@rodfersou vai precisar alterar no overrides.zcml em https://github.com/plonegovbr/brasil.gov.tiles/blob/master/src/brasil/gov/tiles/tiles/overrides.zcml, na propriedade `icon`.

Não precisa de upgradeStep aqui porque ao subir a instância já pega essa propriedade. Estou pensando se não seria o caso de remover esse atributo de uma vez porque aí ele pega do original ao invés do overrides.

**Comment by rodfersou** [comment]
ok, não lembrava de cabeça como isso funciona :)

**Comment by hvelarde** [comment]
@idgserpro infelizmente a gente não tem orçamento para altera nada no brasil.gov.tiles

**Comment by idgserpro** [comment]
Nós iremos tratar essa issue. Obrigado por focarem no collective.cover.

**Comment by idgserpro** [comment]
Fix by https://github.com/plonegovbr/brasil.gov.tiles/pull/141
