### ISSUE TITLE
Tile cabeçalho após a edição do título não carrega o texto alterado

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/brasil.gov.tiles#144]
O tile "cabeçalho" está com um problemas, ao inserir/editar um texto o tile fica em branco, mostrando o texto somente quando é efetuado o refresh da paǵina.

Eu fiz uma correção no meu produto adicionei a classe "tile-content" na linha 8 do arquivo brasil.gov.tiles/src/brasil/gov/tiles/tiles/templates/header.pt, não sei se essa classe é a correta, mas funciona.

```
-    <div class="outstanding-header">
+    <div class="tile-content outstanding-header">
```

**Comment by idgserpro** [comment]
@claytonc poderia nos informar qual versão do brasil.gov.tiles e do IDG que você está usando?

Você pode obter essa info indo em "Configurações do Site", no canto inferior esquerdo tem a versão do Plone. Para ver a do brasil.gov.tiles, vá em "Complementos". Obrigado!

**Comment by claytonc** [comment]
A última versão 1.1.3.1 e utilizando o portal.buildout que utiliza a versão.
