### ISSUE TITLE
Tile banner rotativo com problemas

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/brasil.gov.tiles#145]
O tile banner rotativo esta apresentando problemas.

Após ser populado com as imagens não é possível removê-los clicando no "X" ou movê-las, ficando em branco.

**Comment by idgserpro** [comment]
@claytonc poderia nos informar qual versão do brasil.gov.tiles e do IDG que você está usando?

Você pode obter essa info indo em "Configurações do Site", no canto inferior esquerdo tem a versão do Plone. Para ver a do brasil.gov.tiles, vá em "Complementos". Obrigado!

**Comment by claytonc** [comment]
A última versão 1.1.3.1 e utilizando o portal.buildout que utiliza a versão.

**Comment by osandon** [comment]
Também estamos com o mesmo problema no Banner.

**Comment by osandon** [comment]
Também não estamos conseguindo inserir mais de três notícias no banner.

**Comment by almeidajeff** [comment]
Mesmo problema aconteceu comigo.

Segue versões
    

- Portal Padrão 1.1.3
- brasil.gov.tiles-1.0.7
-     Plone 4.3.3 (4308)
-     CMF 2.2.7
-     Zope 2.13.22
-     Python 2.7.5 (default, Apr 10 2015, 08:09:14) [GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]
-     PIL 2.3.0 (Pillow)

**Comment by almeidajeff** [comment]
@claytonc @osandon @idgserpro 
A solução que apliquei aqui foi implementar o método replace_with_objects que não esta presente no banner_rotativo.py

```
    def replace_with_objects(self, uuids):
        """ Replaces the whole list of items with a new list of items
        :param uuids: The list of objects' UUIDs to be used
        :type uuids: List of strings
        """
        super(BannerRotativoTile, self).replace_with_objects(uuids)  # check permission
        if not self.isAllowedToEdit():
            raise Unauthorized(
                _('You are not allowed to add content to this tile'))
        data_mgr = ITileDataManager(self)
        old_data = data_mgr.get()
        # Clean old data
        old_data['uuids'] = dict()
        data_mgr.set(old_data)
        # Repopulate with clean list
        self.populate_with_uids(uuids)
```

**Comment by idgserpro** [comment]
@almeidajeff, na verdade ele herda esse método do [brasil.gov.tiles.tiles.list.ListTile](https://github.com/plonegovbr/brasil.gov.tiles/blob/master/src/brasil/gov/tiles/tiles/list.py#L131). No entanto, talvez essa implementação não seja mais compatível com a nova versão do collective.cover. Temos que verificar. Relacionado com:

https://github.com/plonegovbr/brasil.gov.tiles/issues/132#issuecomment-182498764

**Comment by smkbarbosa** [comment]
Pra mim, o erro apresentado é o seguinte ao tentar excluir um item do banner rotativo:

HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy
https://paraiso.ifto.edu.br/portal_javascripts/brasil_gov_facetada/resourceplone.app.jquery-cachekey-64ca28e423846a1ff102faf6dacb3a2b.js
Line 14

**Comment by idgserpro** [comment]
@claytonc, o erro indicado pelo @smkbarbosa é o mesmo do seu? Você também está utilizando o ```brasil.gov.facetada```? Pode informar o seu traceback?

**Comment by claytonc** [comment]
@idgserpro sim utilizo.

Como tive que entregar o portal no começo do ano eu sobrescrevi o banner rotativo, as mudanças que fiz foi que agora os banners ficam em uma determinada pasta (sugestão dos provedores de conteúdo), ficou mais simples busco os 4 primeiros banners e a ordenação é a da pasta. 

O css e o js é o mesmo do banner rotativo sem alterações.

**Comment by shogunbr** [comment]
Estamos com o mesmo problema. Ao tentar excluir o item do banner dá o seguinte erro:

2016-08-10 17:31:36 ERROR Zope.SiteErrorLog 1470843096.170.104274255523 http://10.10.12.165:8080/Plone/home/@@removeitemfromlisttile
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module grokcore.view.components, line 151, in __call__
  Module zope.publisher.publish, line 107, in mapply
   - __traceback_info__: <bound method RemoveItemFromListTile.render of <collective.cover.browser.cover.RemoveItemFromListTile object at 0xb4168bcc>>
  Module zope.publisher.publish, line 113, in debug_call
  Module collective.cover.browser.cover, line 340, in render
BadRequest: Invalid parameters

**Comment by hvelarde** [comment]
o código da view está esperando 3 parâmetros: https://github.com/collective/collective.cover/blob/1.1b1/src/collective/cover/browser/cover.py#L332

possivelmente o tile precisa ser atualizado.

**Comment by almeidajeff** [comment]
Me lembro de ter passado por problemas também ao tentar excluir um Item do Tile.
No tempo eu tinha identificado que o uuid sempre estava vindo vazio
https://github.com/collective/collective.cover/blob/1.1b1/src/collective/cover/browser/cover.py#L331

E percebi que no request o correto era 'uid' e não uuid como informado.

**Comment by hvelarde** [comment]
@rodfersou nós que quebramos isso, acho que devemos consertar.

**Comment by rodfersou** [comment]
só mudar de uid para uuid que resolve

**Comment by almeidajeff** [comment]
Na verdade é o contrario @rodfersou , teria que mudar de 
`uuid = self.request.form.get('uuid')`

para
`uuid = self.request.form.get('uid')`

**Comment by rodfersou** [comment]
@almeidajeff de uma olhada nesse pull request por favor https://github.com/plonegovbr/brasil.gov.tiles/pull/166/files

**Comment by almeidajeff** [comment]
Massa @rodfersou é isso mesmo, vi que você corrigiu a questão do método replace_with_objects que eu tinha comentado por aqui tbm.

Show de bola :+1:

**Comment by hvelarde** [comment]
gente, por favor ajudem testar para fazer um release na sequência.

**Comment by smkbarbosa** [comment]
Testei as alterações propostas pelo @almeidajeff e o pull request do @rodfersou, agora retorna esse erro:
`Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module grokcore.view.components, line 151, in __call__
  Module zope.publisher.publish, line 107, in mapply
   - __traceback_info__: <bound method RemoveItemFromListTile.render of <collective.cover.browser.cover.RemoveItemFromListTile object at 0x7f6b886541d0>>
  Module zope.publisher.publish, line 113, in debug_call
  Module collective.cover.browser.cover, line 274, in render
BadRequest: Invalid parameters`

**Comment by smkbarbosa** [comment]
Se manter conforme informado pelo @almeidajeff (https://github.com/plonegovbr/brasil.gov.tiles/issues/145#issuecomment-266748433) retorna **erro 400** ao tentar excluir.

Se manter 
```
 uuid = self.request.form.get('uuid')
```

retorna 204.... exclui da tela no momento, sem registro de erro, mais o banner continua ao voltar para visão do site.

**Comment by smkbarbosa** [comment]
Na console retorna:
```
no element found  @@removeitemfromlisttile:1:1
```

**Comment by rodfersou** [comment]
@smkbarbosa parece que voce precisa cozinhar seus javascripts

**Comment by idgserpro** [comment]
@rodfersou eu testei no modo debug e esse erro realmente ocorre.

**Comment by rodfersou** [comment]
que versão do collective.cover voces estão usando?

```bash
$ grep -i cover bin/instance 
  '/home/rodfersou/.projects/cache/eggs/collective.cover-1.1b1-py2.7.egg',
```

Aqui é **1.1b1** e não consegui ver esse bug.. (se bem que não funcionou a exclusão)

**Comment by rodfersou** [comment]
aqui o problema acontece [nessa linha](https://github.com/collective/collective.cover/blob/1.1b1/src/collective/cover/browser/cover.py#L334) por que o tile banner não herda do tile list ele não remove o item.

**Comment by rodfersou** [comment]
o tile banner rotativo herda da [própria versão do tile list](https://github.com/plonegovbr/brasil.gov.tiles/blob/master/src/brasil/gov/tiles/tiles/list.py#L26) ao invés do [tile list do collective.cover](https://github.com/collective/collective.cover/blob/1.1b1/src/collective/cover/tiles/list.py#L30).

Seria bom rever essa dependencia.. por que precisamos de um tile list diferente do do **collective.cover**? se precisa mesmo de alterações no tile, podemos pelo menos herdar do tile list do cover e depois fazer alterações no **brasil.gov.tiles**.

**Comment by idgserpro** [comment]
@rodfersou veja essa comentário: https://github.com/plonegovbr/brasil.gov.tiles/issues/132#issuecomment-182498764

**Comment by rodfersou** [comment]
@idgserpro se me lembro bem, foi necessário um **overrides.zcml** por que não estava conseguindo fazer sem o override, as configurações do **collective.cover** e **brasil.gov.tiles** estavam entrando em conflito, e fui orientado a trabalhar dessa forma.

Talvez com mais calma e mais tempo seja possível fazer o override somente mudando o layer (como ocorre normalmente em views), mas é bom tomar muito cuidado para não quebrar nada.

A questão de copiar todos os métodos, não estou lembrado se teve algum motivo justificável, o correto seria herdar dos tiles do cover.

Seria bom abrir uma nova issue para tratar somente disso e marcar essa issue como dependência da nova issue.

**Comment by idgserpro** [comment]
A explicação completa do erro está em https://github.com/plonegovbr/brasil.gov.tiles/pull/166#issuecomment-275732680

A correção não é imediata e ainda são precisos estudos resolver esse relato. O PR acima resolve parcialmente.

Para aqueles que precisam dessa funcionalidade, recomendamos criar um patch usando collective.monkeypatcher, alterando o método

https://github.com/collective/collective.cover/blob/1.1b1/src/collective/cover/browser/cover.py#L327

Trocando

`uuid = self.request.form.get('uuid')`

por 

`uuid = self.request.form.get('uid')`

e 

`if IListTile.providedBy(tile):`

por

```
import brasil.gov.tiles.tiles.list.IListTile
if IListTile.providedBy(tile) or brasil.gov.tiles.tiles.list.IListTile.providedBy(tile):
```

Leia a documentação completa de collective.monkeypatcher, é possível aplicar o patch na versão específica do collective.cover. Recomendo criar um novo pacote (meuportal.brasilgovtilespatch ou algo assim) para que esse _workaround_  seja o mais isolado possível.

**Comment by idgserpro** [comment]
Restante será feito na branch https://github.com/plonegovbr/brasil.gov.tiles/tree/issue_145_usa_listtile_cover, específica pra remover o tipo lista.

**Comment by rodfersou** [comment]
@idgserpro não consigo ver esse link

**Comment by idgserpro** [comment]
Isso é apenas uma branch, você não consegue vê-la em https://github.com/plonegovbr/brasil.gov.tiles/branches?

**Comment by idgserpro** [comment]
Prezados (as),

Foi lançada hoje a versão **1.2rc1** desse pacote que corrige de forma paliativa esse problema do Banner Rotativo. A forma mais correta envolve uma reformulação completa do brasil.gov.tiles e ainda está em andamento.

Gostaria de pedir a vocês para testarem, se possível, num ambiente de **homologação** de vocês esse release do brasil.gov.tiles. Não recomendamos em produção ainda porque provavelmente faremos um release do IDG que contemplará esse fix.

Para testar, basta no arquivo de versões de vocês adicionarem `brasil.gov.tiles = 1.2rc1`.

**Comment by idgserpro** [comment]
Foi lançado o release https://github.com/plonegovbr/portalpadrao.release/releases/tag/1.1.5.3 contendo essa versão de brasil.gov.tiles.

**Comment by hvelarde** [comment]
avisem por favor na lista para as pessoas testar.

**Comment by shogunbr** [comment]
Fiz um teste atualizando um portal existente.
Ao clicar no x para remover um item, visualmente todos os itens somem do banner.
Mas, ao recarregar a página de compor, apenas o item em que eu cliquei para remover foi excluído (que é o comportamento esperado).

No console aparece 2x o mesmo warning:

2017-06-27T13:30:13 WARNING plone.protect error parsing dom, failure to add csrf token to response for url http://10.10.12.165:8080/Plone/campus/santahelena/home/@@removeitemfromlisttile
\------
2017-06-27T13:30:13 WARNING plone.protect error parsing dom, failure to add csrf token to response for url http://10.10.12.165:8080/Plone/campus/santahelena/home/@@removeitemfromlisttile

**Comment by idgserpro** [comment]
Sim, como foi afirmado, essa correção é paliativa (via patch), infelizmente ocorre esse efeito colateral de na remoção sumir tudo e ser necessário recarregar.

**Comment by hvelarde** [comment]
@idgserpro acho que o @rodfersou sabe como corrigir isso; tem que adicionar um header na resposta.

**Comment by shogunbr** [comment]
@hvelarde a nova issue seria sobre esse comportamento de sumir tudo ou por causa desse warning do plone.protect?
essas duas coisas estão relacionadas, ou são problemas diferentes?

**Comment by hvelarde** [comment]
@shogunbr são problemas diferentes; seria só sobre isso pois o problema relatado aqui já foi consertado.

**Comment by idgserpro** [comment]
@hvelarde favor ainda não fechar essa issue porque a solução foi aplicando um patch, ainda iremos corrigir de forma definitiva, mas não nesse release.

**Comment by hvelarde** [comment]
@idgserpro sinceramente acho que a issue pode ser fechada e a correção definitiva aplciada em um PR; mas vocês que sabem.

**Comment by idgserpro** [comment]
Como o problema foi resolvido, fecharei o relato porque realmente ficou bem confuso.

O novo relato em https://github.com/plonegovbr/brasil.gov.tiles/issues/181 passa a defender a remoção do patch em definitivo.
