### ISSUE TITLE
Carousel Tile esta com problemas

### ISSUE THREAD

**Issue by claytonc** [plonegovbr/brasil.gov.tiles#146]
Após inserir o "carousel tile" na aba "layout" é gerado o erro abaixo ao clicar em "salvar"  na edição do mesmo e o popup não fecha.

Na aba "compor" também não funciona.

Estou utilizando versão 1.1.3.1 e portal.buildout que utiliza [1].

As versões dos produtos que estou utilizando são todas que estão no [1] nenhum produto foi buscado do github.

[1] https://github.com/plonegovbr/portalpadrao.release/blob/master/1.1.3.1/versions.cfg

```
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module collective.cover.tiles.configuration_view, line 249, in __call__
    Module plone.z3cform.layout, line 66, in __call__
    Module plone.z3cform.layout, line 50, in update
    Module collective.cover.tiles.configuration_view, line 106, in update
    Module plone.app.tiles.browser.base, line 55, in update
    Module plone.z3cform.fieldsets.extensible, line 59, in update
    Module plone.z3cform.patch, line 30, in GroupForm_update
    Module z3c.form.group, line 128, in update
    Module plone.app.tiles.browser.base, line 71, in updateWidgets
    Module z3c.form.field, line 277, in update
    Module z3c.form.browser.textarea, line 37, in update
    Module z3c.form.browser.widget, line 171, in update
    Module z3c.form.widget, line 87, in update
    Module collective.cover.widgets.textlinessortable, line 139, in extract

AttributeError: 'NoneType' object has no attribute 'splitlines' 

```

**Comment by idgserpro** [comment]
@claytonc poderia testar no novo release que está pra ser oficializado, o 1.1.5.2, para ver se o erro persiste?

**Comment by idgserpro** [comment]
@claytonc Alguma novidade?

**Comment by claytonc** [comment]
@idgserpro

Não tenho como testar esse novo release.

Também não pretendo atualizar o portal para o release 1.1.5.2 até o
fechamento da issue #240, pois tive que adicionar patch para indexar os
conteúdos corretamente e a busca do portal atendendo requisitos solicitados
pelo cliente.

Os tiles carrousel, banner rotativo e cabeçalho, foram sobrescritos para
funcionar corretamente para atender os requisitos solicitados pelo cliente
em março/2016.




2017-02-06 17:31 GMT-02:00 idgserpro <notifications@github.com>:

**Comment by idgserpro** [comment]
@claytonc você pode criar um PR para corrigir o relato plonegovbr/brasil.gov.portal#240?

O patch que você fez foi para corrigir o relato plonegovbr/brasil.gov.portal#155?

**Comment by claytonc** [comment]
@idgserpro

Sobre a indexação o que fiz foi aplicar a correção do plone.app.contenttypes 1.1.1 no 1.0 conforme [1],
utilizei o collective.recipe.patch [2] para aplicar os patch.

Agora sobre o problema do carousel baixei hoje o portal.buildout [3] e adicionei o carousel na capa de um portal recém criado, estou utilizando as imagens que estão na pasta "Pastas com exemplos de peças" segue os testes:

- estou conseguindo adicionar;
- estou conseguindo remover;
- as vezes não respeita o tamanho pré-definido, as imagens estão ficando grandes;
- as vezes quando arrasto uma imagem ocorre o seguinte erro "Fatal error:  Could not extract a stage height from the CSS. Traced height: 0px." e para voltar a funcionar tenho que remover a última imagem adicionada e recarregar a página para voltar a funcionar;
- as vezes simplesmente para de funcionar o carousel e ocorre o erro acima e procedimento é o mesmo para voltar a funcionar.

[1] https://github.com/plone/plone.app.contenttypes/blob/1.1.1/plone/app/contenttypes/indexers.py#L37-L60

[2] https://pypi.python.org/pypi/collective.recipe.patch

[3] https://github.com/plonegovbr/portal.buildout

**Comment by idgserpro** [comment]
>Sobre a indexação o que fiz foi aplicar a correção do plone.app.contenttypes 1.1.1 no 1.0 conforme [1]

@claytonc você sabe se existe um upgrade steep no plone.app.contenttypes 1.1 para indexar os conteúdos? Ou teremos que fazer um upgrade quando resolvermos plonegovbr/brasil.gov.portal#240?

**Comment by claytonc** [comment]
@idgserpro tive recatalogar os conteúdos, sem isso os conteúdos antigos não aparecerão na busca.

**Comment by diretoriabco** [comment]
Prezado @idgserpro 

em relação ao seu comentário sobre o carousel: "as vezes não respeita o tamanho pré-definido, as imagens estão ficando grandes;", vc conseguiu resolver isto? se sim, por favor, exigiu programação pelo zope? eu só tenho acesso àquela interface de gerência, mas não ao servidor. Será que consigo resolver este problema sem acesso ao servidor? Meu problema é que as imagens do Carousel nunca redimensionam, ficam sempre gigantescas... rsss

Agradeço pela ajuda!

**Comment by idgserpro** [comment]
@diretoriabco não verifiquei isso mas provavelmente é um problema de css e você vai precisar acessar o servidor para corrigir isso.

**Comment by diretoriabco** [comment]
Muito obrigada! Eu consegui resolver inserindo as figuras já do tamanho
certo, que eu padronizei para 700x70px. Então funcionou direitinho!
Obrigada!

Dra. Eliane Colepicolo (diretoria.bco@ufscar.br)
Diretora BCo
BCo/SiBI/UFSCar
(016) 3351-8422
http://www.bco.ufscar.br
Para agendar reuniões, consulte minha Agenda Pública (https://goo.gl/KusoaM)
.

*"A esperança é algo que traz o sol à sombra de nossas vidas *
*É o vínculo com um amanhã melhor*
*Quando a esperança se vai, *
*também se vai nossa força vital*
*Enquanto a esperança permanece viva,*
*também permanece nossa determinação de prosseguir!"*

*(Yitta Halberstam, Livro Insight, Daniel C. Luz)*


2017-02-23 9:14 GMT-03:00 idgserpro <notifications@github.com>:

**Comment by idgserpro** [comment]
> tive recatalogar os conteúdos, sem isso os conteúdos antigos não aparecerão na busca.

@claytonc Fiquei com uma dúvida aqui. Quando você diz que teve que "recatalogar", você manteve o plone.app.contenttypes 1.0, mas aplicando o patch que vinha do plone.app.contenttypes em https://github.com/plone/plone.app.contenttypes/blob/1.1.1/plone/app/contenttypes/indexers.py#L37-L60? No caso, ao atualizar para plone.app.contenttypes 1.1.1 isso vem automaticamente, certo? Ou você fez algum outro código?

Se fez outro código, quais conteúdos exatamente você precisou recatalogar, e como você fez esse recatalog? Em que momento ele foi feito? Perguntamos isso pois encontramos um bug na migração do tipo Evento no Plone, [abrindo um relato](https://github.com/plone/Products.contentmigration/issues/16) e fizendo um [patch](https://github.com/plonegovbr/brasil.gov.portal/pull/366) (pois não sabemos quando será consertado upstream).

**Comment by idgserpro** [comment]
@claytonc Sobre o erro desse relato, favor testar o release 1.1.5.3, que possui um release novo do brasil.gov.tiles pra ver se resolve o problema.

**Comment by hvelarde** [comment]
esse problema aqui ainda é válido?

**Comment by diretoriabco** [comment]
Bom dia!

Já foi resolvido!
Obrigada!

Marisa Cubas Lozano (diretoria.bco@ufscar.br)
Diretora BCo
BCo/SiBI/UFSCar
(016) 3351-8422
http://www.bco.ufscar.br
Para agendar reuniões, consulte minha Agenda Pública (https://goo.gl/KusoaM)
.


Em qui, 30 de ago de 2018 às 15:38, Héctor Velarde <notifications@github.com>
escreveu:
