### ISSUE TITLE
Novo release 1.0.8

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#152]
@hvelarde @winstonf88 poderiam nos auxiliar com a geração de um novo release do pacote?

**Comment by hvelarde** [comment]
tem testes falhando; não posso fazer release até isso ser consertado:

https://travis-ci.org/plonegovbr/brasil.gov.tiles/builds/134619606

**Comment by idgserpro** [comment]
Favor ainda não gerar o releas: ver https://github.com/plonegovbr/brasil.gov.tiles/pull/155

**Comment by hvelarde** [comment]
posso fazer release agora?

**Comment by idgserpro** [comment]
Acredito que o PR https://github.com/plonegovbr/portalpadrao.release/pull/9 deva ser mesclado, o diretório alterado de "1.1.4-pending" para "1.1.4", e modificarmos a linha no buildout.cfg de brasil.gov.tiles onde referenciamos "1.1.4-pending" para "1.1.4", antes da geração do release.

**Comment by idgserpro** [comment]
Pode gerar a tag no github e o release no pypi.

**Comment by hvelarde** [comment]
release feito: https://pypi.python.org/pypi/brasil.gov.tiles/1.1rc1
