### ISSUE TITLE
Versão 1.1b1 do collective.cover quebra o tile de carrossel em brasil.gov.tiles 1.1rc1

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#156]
Isso acontece porque aqui em brasil.gov.tiles faz referência aos recursos do galleria em

```javascript
++resource++collective.cover/galleria-theme/galleria.cover_theme.js
```

Mas o caminho na versão nova do cover mudou no commit https://github.com/collective/collective.cover/commit/86a9972f859c59d18329ffd3a29b4d5190c9dece, ficando

```javascript
++resource++collective.cover/js/galleria.cover_theme.js
```

![selecao_176](https://cloud.githubusercontent.com/assets/8203476/16162303/e872d7b2-34a8-11e6-815f-b5a5383bd6cf.png)

Precisamos mudar todas as referências no pacote a esse caminho antigo pro novo e estudar uma forma disso não precisar ser manual como é hoje (se possível, resolver https://github.com/collective/collective.cover/issues/613 para que fique tudo como um recurso js para não ter que ficar fazendo essas chamadas manuais).

Além disso, esse tile não tem um teste de robot, por isso esse erro não conseguiu ser pego na infra estrutura de testes, portanto ele também precisa ser criado.

**Comment by hvelarde** [comment]
no mesmo collective.cover podem ver o upgrade step que fizemos para consertar isso.

**Comment by idgserpro** [comment]
Há impacto em outras partes desse pacote, por exemplo no vídeo, ver https://github.com/plonegovbr/brasil.gov.tiles/search?utf8=%E2%9C%93&q=galleria

@hvelarde @rodfersou Prezados, seria o caso de removermos 
https://github.com/plonegovbr/brasil.gov.tiles/blob/baa8547302291a9d4de19ead8eb8d9454f853cb5/src/brasil/gov/tiles/static/galleria.classic.css 

e 

https://github.com/plonegovbr/brasil.gov.tiles/commits/134b150b1e642e1d5304ebb7d42ad0fad5a0b090/src/brasil/gov/tiles/static/galleria.classic.min.js

uma vez que temos os mesmos em 

https://github.com/collective/collective.js.galleria/blob/6afe045d4ab26861f0604bad63b82e781ec7a3ed/collective/js/galleria/resources/themes/classic/galleria.classic.css 

e 

https://github.com/collective/collective.js.galleria/blob/6afe045d4ab26861f0604bad63b82e781ec7a3ed/collective/js/galleria/resources/themes/classic/galleria.classic.js 

e collective.js.galleria é [dependência de collective.cover](https://github.com/collective/collective.cover/blob/d06bcc17b80925756c4e6c578d3637b6fcff3be9/setup.py#L48)?

**Comment by hvelarde** [comment]
@idgserpro fiquem a vontade de consertar qualquer coisa que precisar conserto.

**Comment by idgserpro** [comment]
@hvelarde mesmo corrigindo o caminho do js, a tile de carrossel do ```brasil.gov.tiles``` não funciona porque o js [++resource++collective.cover/js/galleria.cover_theme.js](https://github.com/collective/collective.cover/blob/master/src/collective/cover/static/js/galleria.cover_theme.js) do ```collective.cover```, mudou bastante e já não funciona mais com o código do ```brasil.gov.tiles```.

Estou querendo remover a customização do carrossel do ```brasil.gov.tiles``` e passar a utilizar carrossel do ```collective.cover``` . No entando, vejo a intenção de remover o carrossel do cover:

https://github.com/collective/collective.cover/issues/485

Qual a sua opinião sobre esse assunto?

**Comment by hvelarde** [comment]
@idgserpro remover o tile de carrossel não é uma coisa trivial e não temos pressa por enquanto.

tal vez a melhor solução seja rescrever o tile do brasil.gov.tiles e utilizar o Cycle2 nele.

**Comment by rodfersou** [comment]
@idgserpro pode ver como foi feito na visão de albuns que usa cycle2 https://github.com/plonegovbr/brasil.gov.portal/tree/master/src/brasil/gov/portal/browser/album

**Comment by idgserpro** [comment]
@hvelarde @rodfersou a ideia não era remover completamente a tile de carrossel mas sim substituir pela tile do cover, uma vez o ```brasil.gov.title``` [sobrescrever a tile de carrossel do cover](https://github.com/plonegovbr/brasil.gov.tiles/blob/007adcde40d2031a15debd5122af8086a1db6fa6/src/brasil/gov/tiles/tiles/overrides.zcml#L145-L155). Isso pouparia esforços, uma vez que a tile de carrossel já está implementada no cover. Assim poderiamos consentrar os esforços na evolução da tile do cover.
