### ISSUE TITLE
Erro ao salvar a configuração do Carousel Tile

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#159]
Ao clicarmos nas configurações do carousel tile abrimos a caixa de dialogo "Configurar Carousel Tile", após efetuarmos as modificações nas configurações do tile ao clicarmos no botão salvar não acontece nada, ou seja não salva e nem fecha a caixa de diálogo de configuração.

**Comment by hvelarde** [comment]
tem algum traceback? algo na consola de JS?

**Comment by idgserpro** [comment]
Não, não acontece nada quando clicamos no botão salvar, e a caixa de diálogo permanece até a fecharmos.

**Comment by claytonc** [comment]
Já existe uma issue #146
