### ISSUE TITLE
Erro no painel de controle para o upgradeStep 4001

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#167]
No release 1.1.5.2 do IDG, ocorre esse erro. Faltou atualizar o metadata.xml.

![selecao_007](https://cloud.githubusercontent.com/assets/8203476/21997087/80daadb4-dc14-11e6-851b-66e994a65dc1.png)

Recomendo adicionar um teste como [o presente em brasil.gov.portal](https://github.com/plonegovbr/brasil.gov.portal/blob/07f939993d6e9510372895cd8f09262b27de3788/src/brasil/gov/portal/tests/test_setup.py#L675) para evitar que esse erro ocorra novamente.

**Comment by hvelarde** [comment]
esse problema ainda acontece?

**Comment by idgserpro** [comment]
@hvelarde o teste foi adicionando mas no master ele está sendo pulado:

https://github.com/plonegovbr/brasil.gov.tiles/blob/3186fd785def349a0039ffe4abc384c1cdc3c90a/src/brasil/gov/tiles/tests/test_setup.py#L59

Ele ainda precisa ser pulado?
