### ISSUE TITLE
Remover tiles duplicados

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#171]
Banner, Basic, Collection, Embed existem tanto aqui quanto em collective.cover: ver se são muito diferentes e, caso sejam similares, migrar para usar os do cover.

**Comment by rodfersou** [comment]
Pull requests:
https://github.com/plonegovbr/brasil.gov.tiles/pull/209
https://github.com/plonegovbr/brasil.gov.tiles/pull/208
https://github.com/plonegovbr/brasil.gov.tiles/pull/207
https://github.com/plonegovbr/brasil.gov.tiles/pull/206
https://github.com/plonegovbr/brasil.gov.tiles/pull/205

**Comment by rodfersou** [comment]
@hvelarde vamos fazer um upgrade step para substituir os tiles antigos para os novos nesses PR? ou fazemos isso em um momento posterior?

**Comment by rodfersou** [comment]
Após mesclar esses pull requests podemos remover esta dependencia https://github.com/plonegovbr/brasil.gov.tiles/blob/master/setup.py#L94

**Comment by hvelarde** [comment]
não precisa de um upgrade step para remover os overrides pois os nomes são os mesmos (possivelmente só no caso do tile NITF, mas vamos deixar para mais na frente).

**Comment by rodfersou** [comment]
@hvelarde mesmo os nomes sendo os mesmos, precisa de uma substituição dos dados dos tiles já criados, pois existem diferenças nos nomes dos campos de configuração dos tiles.

**Comment by hvelarde** [comment]
isso aqui está sendo feito já no IDG v2.
