### ISSUE TITLE
Podemos usar a classe do embed direto do sc.embedder/collective.cover ao invés de reimplementar aqui?

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#172]
Verificar se podemos customizar apenas a template, devido a peculiaridades do brasil.gov.portal.

https://github.com/simplesconsultoria/sc.embedder/blob/82183732dec9a1489ab9dea2f07259c367ab365f/src/sc/embedder/tiles/embedder.py

https://github.com/plonegovbr/brasil.gov.tiles/blob/28200bc14ab2b54cbb0623969cf5c157d064e2b1/src/brasil/gov/tiles/tiles/embed.py

**Comment by hvelarde** [comment]
o tile do sc.embedder não está fazendo muito sentido para mim; sou mais da ideia de reutilizar o próprio tile do cover para isso, só teríamos que adaptar seu funcionamento se o sc.embeder está instalado.

**Comment by idgserpro** [comment]
Pode ser estudado também

**Comment by hvelarde** [comment]
o sc.embedder é agora uma dependência do IDG v2.
