### ISSUE TITLE
Chamada de arquivo em javascript deveria ser em jsregistry.xml

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#175]
Essa é a mesma situação que https://github.com/collective/collective.cover/issues/613, mas específica para esse pacote (https://github.com/plonegovbr/brasil.gov.tiles/blob/74d45e30e956d274bdddcb12f255fd78417f484a/src/brasil/gov/tiles/tiles/templates/banner_rotativo.pt#L8).

**Comment by hvelarde** [comment]
no IDG v2 os recursos estáticos são processados usando o webpack e adicionados no registry (refs. #204).
