### ISSUE TITLE
Remover patch to tile banner rotativo que foi adicionado após atualizar o cover e corrigir de forma definitiva

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#181]
Motivado por https://github.com/plonegovbr/brasil.gov.tiles/issues/145. No PR https://github.com/plonegovbr/brasil.gov.tiles/pull/173 isso começou a ser tratado. Explicação completa do erro em https://github.com/plonegovbr/brasil.gov.tiles/pull/166#issuecomment-275732680.

Lembrar de ver a questão do csrf (https://github.com/plonegovbr/brasil.gov.tiles/issues/145#issuecomment-311336191).

**Comment by claytonc** [comment]
Na versão do IDG 1.3 indo para 1.4 o tile Carrossel ocorre o seguinte erro ao tentar excluir um item

http://localhost:8080/Plone/home/@@removeitemfromlisttile
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module collective.cover.browser.compose, line 174, in __call__
  Module brasil.gov.tiles.patches_banner_rotativo, line 60, in render
TypeError: render() takes exactly 1 argument (2 given)

**Comment by hvelarde** [comment]
@claytonc por favor abre uma issue no brasil.gov.portal visualizar todo no milestone 1.4.

**Comment by idgserpro** [comment]
@claytonc não entendi. Ocorre o erro na 1.3 ou na 1.4?

É um bug mesmo, foi feito um patch mas o correto é mexer em https://github.com/plonegovbr/brasil.gov.tiles/pull/173

**Comment by idgserpro** [comment]
Poderia dar um print em https://github.com/plonegovbr/brasil.gov.tiles/blob/d7891fd6584f687e5d18c5d9e06aad7bafedc4c7/src/brasil/gov/tiles/patches_banner_rotativo.py#L56? Era pra cair no if do "banner_rotativo" mas está entrando no else.

**Comment by idgserpro** [comment]
Ah, me desculpe, tile Carrossel e não "banner_rotativo".

**Comment by claytonc** [comment]
@idgserpro 
Ocorreu nas duas versões, pensei que um erro exclusivo da 1.4 mas testei também na 1.3 e ocorreu o mesmo problemas.

**Comment by claytonc** [comment]
@idgserpro 

Eu sugiro se for possível e fácil a remoção do item "excluir" do tile Carrossel e deixar a exclusão ser feita link Editar como hoje, pois ocorre outro problema que é "Could not extract a stage height from the CSS. Traced height: 0px." e só editando e removendo o item problemático que ele volta a funcionar.

**Comment by hvelarde** [comment]
no IDG v2 o banner rotativo está descontinuado e esse patch foi removido (refs. #239).
