### ISSUE TITLE
Carrossel Multimídia não funciona

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#186]
A transição de uma imagem pra outra de forma automática não funciona. Testado em 36338582e5ae608d64a15c2ae6c8462fcc6cfd83. Ao corrigir, ver se é possível adicionar um teste para ter certeza que a transição está funcionando em https://github.com/plonegovbr/brasil.gov.tiles/blob/master/src/brasil/gov/tiles/tests/test_mediacarousel_tile.robot.

**Comment by hvelarde** [comment]
isso ainda acontece?

**Comment by idgserpro** [comment]
Sim. Para simular, adicione um carrossel multimídia: na sequência, em "adicionar conteúdo", selecione "árvore de conteúdo", pasta "imagens" arraste o item "coleção de imagens". Você verá que o primeiro item até tem uma transição mas o restante fica parado.

**Comment by hvelarde** [comment]
no IDG v2 o tile de Carrossel multimídia foi descontinuado (refs. #233).
