### ISSUE TITLE
Patch do tile banner rotativo quebra o tile de carrossel

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.tiles#192]
Reportado por @claytonc:

Na versão do IDG 1.3 indo para 1.4 o tile Carrossel ocorre o seguinte erro ao tentar excluir um item

http://localhost:8080/Plone/home/@@removeitemfromlisttile
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module collective.cover.browser.compose, line 174, in call
Module brasil.gov.tiles.patches_banner_rotativo, line 60, in render
TypeError: render() takes exactly 1 argument (2 given)

Testando no IDG 1.1.5.3, ocorre o mesmo erro, portanto, isso não foi adicionado na atualização de 1.2 ou 1.3.

Discussão inicial foi em https://github.com/plonegovbr/brasil.gov.tiles/issues/186.

**Comment by hvelarde** [comment]
acredito que podemos corrigir este problema na versão 1.5 então.

**Comment by idgserpro** [comment]
Tem de tirar o self em https://github.com/plonegovbr/brasil.gov.tiles/blob/f885abe899c1ad6eec7df8a6ac2fe60e73176e0d/src/brasil/gov/tiles/patches_banner_rotativo.py#L60.

Depois o ideal mesmo é https://github.com/plonegovbr/brasil.gov.tiles/issues/181, porque o PR adiciona também testes para os tiles.

**Comment by hvelarde** [comment]
não é mais simples um PR seu?

**Comment by rodfersou** [comment]
Eu não consegui simular o problema aqui, mas aparentemente o problema é que deveria ser:

```python
self._old_render()
```
ao invés de 
```python
self._old_render(self)
```
