### ISSUE TITLE
Suporte a Instagram no tile `Social`

### ISSUE THREAD

**Issue by tcurvelo** [plonegovbr/brasil.gov.tiles#211]
No tile Social hoje é possível exibir feeds do Twitter e/ou Facebook.
Tem alguém trabalhando em algo parecido para o Instagram?

**Comment by hvelarde** [comment]
nós fizemos isso no site das [Olimpíadas 2016](http://www.brasil2016.gov.br/pt-br) olha no fundo da tela; posso te dar acesso ao repositório se quiser.

**Comment by idgserpro** [comment]
Não seria melhor, se realmente for atuar nisso, ver como incorporar em https://github.com/collective/sc.social.like?

**Comment by tcurvelo** [comment]
Obrigado, @hvelarde :+1: 
Vou olhar o repositório das olimipiadas
