### ISSUE TITLE
Definir quais tiles devem entrar no IDG 2.x

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.tiles#218]
@idgserpro voce poderia por favor ajudar a definir quais tiles permanecem, e quais devem ser removidos ou adicionados para o IDG 2.x?

Segue uma planilha que estamos tentando utilizar para organizar o novo release:
https://docs.google.com/spreadsheets/d/1bqvm7MfBjwAFw6DizVxBZBs5rrflSq4-y65svuE8MF0/edit#gid=0

**Comment by hvelarde** [comment]
ver #220
