### ISSUE TITLE
Revisar tradução do pacote

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.tiles#26]
Hoje os tiles estão utilizando a factory de tradução do collective.cover.

Precisamos revisar e modificar para utilizar a tradução do brasil.gov.tiles tão bem quanto criar os arquivos de tradução .po .pot necessários.

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by rodfersou** [comment]
Dei uma pesquisada, e boa parte dos problemas se foram, só o tile Basic (customizado do c.cover) que está utilizando a factory do cover hoje https://github.com/plonegovbr/brasil.gov.tiles/blob/69f4395f79680ff8d39e91ef16bd378bd941426d/src/brasil/gov/tiles/tiles/basic.py#L5

Esta customização foi necessária por adicionar a opção de variação de título https://github.com/plonegovbr/brasil.gov.tiles/blob/69f4395f79680ff8d39e91ef16bd378bd941426d/src/brasil/gov/tiles/tiles/basic.py#L70-L79

@hvelarde acredito que devemos trazer as traduções do c.cover para este pacote também, concorda?

**Comment by rodfersou** [comment]
Olhei com um pouco mais de cuidado, e além desse tile, temos templates utilizando a factory do cover:

* https://github.com/plonegovbr/brasil.gov.tiles/blob/9cab001210cfe19ba5c29629650cf9b7d1bfbcf7/src/brasil/gov/tiles/tiles/templates/embed.pt#L5
* https://github.com/plonegovbr/brasil.gov.tiles/blob/69f4395f79680ff8d39e91ef16bd378bd941426d/src/brasil/gov/tiles/tiles/templates/banner.pt#L5
* https://github.com/plonegovbr/brasil.gov.tiles/blob/aaed27ea266c4a7bf9f6c2786455d557d2b5f3b9/src/brasil/gov/tiles/tiles/templates/basic.pt#L5
* https://github.com/plonegovbr/brasil.gov.tiles/blob/9cab001210cfe19ba5c29629650cf9b7d1bfbcf7/src/brasil/gov/tiles/tiles/templates/list.pt#L5
* https://github.com/plonegovbr/brasil.gov.tiles/blob/cdd483a552c12fdbc271a4bea30d240aaa57be14/src/brasil/gov/tiles/tiles/templates/collection.pt#L5
* https://github.com/plonegovbr/brasil.gov.tiles/blob/9cab001210cfe19ba5c29629650cf9b7d1bfbcf7/src/brasil/gov/tiles/tiles/templates/mediacarousel.pt#L5

**Comment by idgserpro** [comment]
@rodfersou Você vai mexer nessas correções?

**Comment by rodfersou** [comment]
@hvelarde @Dadlo @idgserpro eu levantei a questão sobre o problema, voces acham válido seguir com essa alteração?

Outra questão interessante seria re-ver todas as strings que não estão preparadas para tradução hoje.

**Comment by rodfersou** [comment]
@idgserpro alguém requisitou tradução dos pacotes plonegovbr ?

**Comment by idgserpro** [comment]
@rodfersou sim, estamos mexendo no brasil.gov.agenda e iria mexer no brasil.gov.tiles mas vi esse seu relato, por isso meu questionamento.

**Comment by rodfersou** [comment]
@idgserpro infelizmente não vou ter muito tempo para trabalhar na tradução desse pacote, mas vou acompanhar a conversa e ajudar no que puder.

**Comment by idgserpro** [comment]
O collective.cover é [dependência explícita do brasil.gov.tiles como previsto no setup.py](https://raw.githubusercontent.com/plonegovbr/brasil.gov.tiles/8fe95e4f83068db0375d1774006c4a9c6e193874/setup.py). Analisando nesse contexto específico, não vejo necessidade de replicar essas strings em brasil.gov.tiles. Revisando todas essas traduções, elas estão presentes no collective.cover.po e considero não haver mais ação necessária.

As únicas strings que vi que precisam de correção (no caso, ir para o domínio brasil.gov.tiles) estão presentes em nosso [pull request](https://github.com/plonegovbr/brasil.gov.tiles/pull/128) (Os testes irão falhar pois é necessário corrigir o #125, erro do 'frontpage'. @hvelarde, qual a melhor forma de corrigir esse teste? Poderia arrumar?). Foi também efetuada uma correção nos arquivos ```*.po```de tradução em espanhol.

Com relação a outras strings de tradução presentes no campo Choices dos tiles, essa discussão é mais ampla e definida como ação futura no relato #123 (gerou inclusive um [pull request emergencial](https://github.com/plonegovbr/brasil.gov.tiles/pull/124/) quando tentou se alterar sem maiores testes) mesmo porque não são relativas a traduções para o usuário final. Achei melhor abrir o relato #127 para tratar esse assunto em específico ao invés de termos issues muito genéricos como esse em específico. 

Isto posto, acredito que esse relato possa ser encerrado. @hvelarde, opiniões?

**Comment by hvelarde** [comment]
@idgserpro acho que tem que herdar da clase ``collective.cover.tests.base.TestTileMixin`` como pode ser visto aqui:

https://github.com/collective/collective.cover/commit/61441e3742be5611c51dc8edab0dddeec4babf3f#diff-1ef23fab108e49fc3fedcacd2d031d32R11

aqui tem um exemplo mais recente:

https://github.com/collective/collective.nitf/blob/master/src/collective/nitf/tests/test_nitf_tile.py
