### ISSUE TITLE
Definir novos ícones para tiles do cover (Aba Layout)

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.tiles#40]
Criar novos ícones para tiles do cover baseando o estilo dos ícones existenstes.

![icones_cover](https://f.cloud.github.com/assets/131209/1126149/2b117fb6-1b1f-11e3-9f4f-6236abde9517.png)

**Comment by hvelarde** [comment]
resolvido nas novas versões do pacote.
