### ISSUE TITLE
Revisão template tile social

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.tiles#48]
Foi identificado que existe urls estáticas no tile social, que devem ser re-pensadas.

https://github.com/plonegovbr/brasil.gov.tiles/blob/master/src/brasil/gov/tiles/tiles/templates/social.pt#L63-L68

**Comment by hvelarde** [comment]
isso ainda é válido ou podemos fechar?

**Comment by rodfersou** [comment]
Sim, ainda é válido

**Comment by rodfersou** [comment]
@Dadlo acredito que podemos remover as linhas https://github.com/plonegovbr/brasil.gov.tiles/blob/master/src/brasil/gov/tiles/tiles/templates/social.pt#L63-L68 e levar este código https://github.com/plonegovbr/brasil.gov.tiles/blob/master/src/brasil/gov/tiles/tiles/templates/social.pt#L9-L12 para o arquivo https://github.com/plonegovbr/brasil.gov.tiles/blob/master/src/brasil/gov/tiles/static/tiles.js concorda?

**Comment by hvelarde** [comment]
o tile foi removido do IDG v2 (refs: #237).
